INSERT INTO genre (name)
VALUES
    ('Rock'),
    ('Pop'),
    ('Ballad'),
    ('Jazz'),
    ('Disco'),
    ('Hip Hop'),
    ('Classical'),
    ('Electronic'),
    ('Reggae'),
    ('R&B'),
    ('Country'),
    ('Funk'),
    ('Blues'),
    ('Metal'),
    ('Soul'),
    ('Punk'),
    ('Indie'),
    ('Folk'),
    ('EDM'),
    ('Alternative');
